# Default values for ..
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3
restartPolicy: Always

image:
  repository: nexflare73/cve-consumer
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

# Image pull secrets
# imagePullSecrets:
#   resourceName: myregistrykey
imagePullSecrets: 
  myregistrykey: 
nameOverride: cve-consumer
fullnameOverride: ""

flywaySchema: "cve"
flywayDefaultSchema: "cve"
flywayLocation: "sql/migrations"

initContainer:
  name: "db-migration"
  image: "nexflare73/webapp-cve-migration:latest"

dbCredentials:
  dbHost: ""
  dbUser: ""
  # add your password here
  dbPassword: ""
  dbName: ""
  dbPort: ""
  batchSize: ""
  dbUrl: "jdbc:postgresql://cve-db-postgresql-ha-pgpool:5432/cve"

kafka:
  username: ""
  password: ""
  topic: ""
  groupId: ""
  broker: ""

readinessProbe:
  exec:
    command:
      - "./build/readiness"
  initialDelaySeconds: 20
  periodSeconds: 20
  timeoutSeconds: 15
  failureThreshold: 5
  successThreshold: 1

livenessProbe:
  exec:
    command:
      - "./build/liveness"
  initialDelaySeconds: 20
  periodSeconds: 20
  timeoutSeconds: 15
  failureThreshold: 5
  successThreshold: 1

