# Default values for ..
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3
restartPolicy: Always

image:
  repository: nexflare/cve-consumer
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

# Image pull secrets
# imagePullSecrets: 
#   - resourceName: myregistrykey
imagePullSecrets: {}
nameOverride: cve-consumer
fullnameOverride: ""

initContainer:
  name: "db-migration"
  image: "nexflare73/webapp-cve-migration:latest"

dbCredentials:
  dbHost: "postgres-service"
  dbUser: ""
  # add your password here
  dbPassword: ""
  dbName: "cve"
  dbPort: "5432"
  batchSize: "1"
  dbUrl: "jdbc:postgresql://postgres-service:5432/cve"

readinessProbe:
  exec:
    command: 
      - "./build/readiness"
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 5
  successThreshold: 1
  