# Default values for ..
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3
restartPolicy: Always

image:
  repository: nexflare73/webapp-cve-consumer
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.2.0"

# Image pull secrets
# imagePullSecrets:
#   - secret1
#   - secret2
imagePullSecrets: 
  - docker-secret
nameOverride: cve-consumer
fullnameOverride: ""

flywaySchema: "cve"
flywayDefaultSchema: "cve"
flywayLocation: "sql/migrations"

initContainer:
  name: "db-migration"
  image: "nexflare73/webapp-cve-migration:latest"

dbCredentials:
  dbHost: "cve-db-postgresql-ha-pgpool"
  dbUser: ""
  # add your password here
  dbPassword: ""
  dbName: ""
  dbPort: "5432"
  batchSize: "1"
  dbUrl: "jdbc:postgresql://cve-db-postgresql-ha-pgpool:5432/cve"

kafka:
  username: ""
  password: ""
  topic: "cve-data-push"
  groupId: "cve-consumer-group"
  broker: kafka-controller-0.kafka-controller-headless.default.svc.cluster.local:9092;kafka-controller-1.kafka-controller-headless.default.svc.cluster.local:9092;kafka-controller-2.kafka-controller-headless.default.svc.cluster.local:9092


readinessProbe:
  exec:
    command:
      - "./build/readiness"
  initialDelaySeconds: 5
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 5
  successThreshold: 1

livenessProbe:
  exec:
    command:
      - "./build/liveness"
  initialDelaySeconds: 10
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 5
  successThreshold: 1

resources: 
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 30m
    memory: 256Mi

podLabels:
  app: cve-consumer


rollingUpdate:
  maxUnavailable: 0
  maxSurge: 1

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 15
  # targetMemoryUtilizationPercentage: 80

rbac:
  create: true
  # additonal Rules
  # - apiGroups: [""]
  #   resources: ["pods"]
  #   verbs: ["get", "list"]
  extraRules: []

pdb:
  create: true
  # minAvailable: 1
  maxUnavailable: 1
  annotations: {}