apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "..fullname" . }}
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "..selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "..labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: {{ .Values.restartPolicy }} 
      imagePullSecrets:
        {{- include "webapp-cve.imagePullSecrets" . | nindent 8 }}
      initContainers:
        - name: {{ .Values.initContainer.name }}
          image: {{ .Values.initContainer.image }}
          env:
            - name: FLYWAY_URL
              valueFrom:
                configMapKeyRef:
                  name: db-values-cfgmp
                  key: DB_URL
            - name: FLYWAY_USER
              valueFrom:
                configMapKeyRef:
                  name: db-values-cfgmp
                  key: DB_USER
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
          envFrom:
            - configMapRef:
                name: db-values-cfgmp
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: db-values-cfgmp
            - secretRef:
                name: db-credentials
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}