apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-webapp-cve-consumer.fullname" . }}
  labels:
    {{- include "helm-webapp-cve-consumer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm-webapp-cve-consumer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm-webapp-cve-consumer.commonLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: {{ .Values.restartPolicy }} 
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- include "helm-webapp-cve-consumer.selectorLabels" . | nindent 20 }}
                topologyKey: "kubernetes.io/hostname"
      imagePullSecrets:
        {{- include "helm-webapp-cve-consumer.imagePullSecrets" . | nindent 8 }}
      initContainers:
        - name: {{ .Values.initContainer.name }}
          image: {{ .Values.initContainer.image }}
          env:
            - name: FLYWAY_URL
              valueFrom:
                configMapKeyRef:
                  name: db-values-cfgmp
                  key: DB_URL
            - name: FLYWAY_USER
              valueFrom:
                configMapKeyRef:
                  name: db-values-cfgmp
                  key: DB_USER
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
          envFrom:
            - configMapRef:
                name: db-values-cfgmp
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: db-values-cfgmp
            - secretRef:
                name: db-credentials
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
      maxUnavailable: 1
      maxSurge: 1