---
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "helm-webapp-cve-consumer.labels" . | nindent 4 }}
  name: {{ include "helm-webapp-cve-consumer.fullname" . }}-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "helm-webapp-cve-consumer.roleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "helm-webapp-cve-consumer.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}