---
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "helm-webapp-cve-consumer.labels" . | nindent 4 }}
  name: {{ include "helm-webapp-cve-consumer.roleName" . }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
{{- with .Values.rbac.extraRules }}
{{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}